apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-deployment
  namespace: ticketing-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis 
  template:
    metadata:
      labels:
        app: expiration-redis 
    spec:
      containers:
        - name: expiration-redis 
          image: redis

---

apiVersion: v1
kind: Service
metadata:
  name:  expiration-redis-srv
  namespace: ticketing-ns
spec:
  type: ClusterIP
  selector:
    app: expiration-redis 
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
