apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
  namespace: ticketing-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: ammuuu/payments
          env:
            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing

            # Each ticketing client must be an unique client connecting to the same NATS server
            # As each pod will have its own unique ID, this can be used as the client ID
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---

apiVersion: v1
kind: Service
metadata:
  name: payments-srv
  namespace: ticketing-ns
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
